-- Run once in Supabase > SQL Editor before using staff account login.

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique,
  display_name text not null,
  role text not null check (role in ('inventory', 'admin', 'super_admin')),
  active boolean not null default true,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.admin_profiles add column if not exists username text;
alter table public.admin_profiles add column if not exists must_change_password boolean not null default false;
update public.admin_profiles set username = lower(split_part(email, '@', 1)) where username is null;
alter table public.admin_profiles alter column username set not null;
create unique index if not exists admin_profiles_username_idx on public.admin_profiles (username);

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_name text,
  actor_role text not null,
  actor_type text not null check (actor_type in ('account', 'emergency')),
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_logs_created_idx on public.admin_activity_logs (created_at desc);
alter table public.admin_profiles enable row level security;
alter table public.admin_activity_logs enable row level security;

-- No public policies: these tables are accessed only by trusted server routes.
