'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import { CalendarDays, Check, ChefHat, ChevronDown, CircleDollarSign, ClipboardList, Download, Eye, Filter, Layers3, Loader2, LockKeyhole, LogOut, Mail, MapPin, Phone, Plus, RefreshCw, Save, Settings2, Store, UserRound, Utensils, X } from 'lucide-react';
import { normalizeImageUrl } from '@/lib/images';

const money = (v) => `₱${Number(v || 0).toFixed(2)}`;
const emptyData = { restaurants: [], categories: [], menuItems: [], optionGroups: [], options: [], guests: [] };
const statuses = ['pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled'];
const CACHE_KEY = 'tmg-admin-snapshot-v1';
const dateKey = (value) => {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat('en-CA', { timeZone:'Asia/Manila', year:'numeric', month:'2-digit', day:'2-digit' }).format(date);
};
const todayKey = () => dateKey(new Date());
async function request(action, body) {
  const response = await fetch(body ? '/api/admin' : `/api/admin?action=${encodeURIComponent(action)}`, body ? {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ action, ...body }),
  } : { cache: 'no-store' });
  const result = await response.json();
  if (!response.ok || result.error) throw new Error(result.error || 'Request failed.');
  return result;
}

export default function AdminClient() {
  const [tab, setTab] = useState('orders');
  const [orders, setOrders] = useState([]);
  const [data, setData] = useState(emptyData);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [editor, setEditor] = useState(null);
  const [saving, setSaving] = useState(false);
  const [reportDate, setReportDate] = useState(todayKey);
  const [expandedOrder, setExpandedOrder] = useState(null);
  const [menuRestaurant, setMenuRestaurant] = useState('all');
  const [addonCategory, setAddonCategory] = useState('all');

  const load = useCallback(async () => { setLoading(true); setError(''); try { let snapshot; try { snapshot = await request('getAdminSnapshot'); } catch { const [orderRows,adminData]=await Promise.all([request('getOrders'),request('getAdminData')]); snapshot={...adminData,orders:orderRows}; } setOrders(Array.isArray(snapshot.orders)?snapshot.orders:[]); setData({ ...emptyData, ...snapshot }); localStorage.setItem(CACHE_KEY,JSON.stringify(snapshot)); } catch(e) { setError(e.message); } finally { setLoading(false); } }, []);
  useEffect(() => { try { const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||'null'); if(cached){setOrders(cached.orders||[]);setData({...emptyData,...cached});setLoading(false);} } catch {} load(); }, [load]);
  const reportOrders = useMemo(() => orders.filter(order => dateKey(order.created_at) === reportDate), [orders,reportDate]);
  const filteredCategories = useMemo(() => menuRestaurant === 'all' ? data.categories : data.categories.filter(category => String(category.restaurant_id) === menuRestaurant), [data.categories,menuRestaurant]);
  const filteredMenuItems = useMemo(() => menuRestaurant === 'all' ? data.menuItems : data.menuItems.filter(item => String(item.restaurant_id) === menuRestaurant), [data.menuItems,menuRestaurant]);
  const filteredGroups = useMemo(() => addonCategory === 'all' ? data.optionGroups : data.optionGroups.filter(group => String(group.category_id) === addonCategory), [data.optionGroups,addonCategory]);
  const filteredOptions = useMemo(() => { if(addonCategory==='all') return data.options; const groupIds=new Set(filteredGroups.map(group=>String(group.group_id))); return data.options.filter(option=>groupIds.has(String(option.group_id))); }, [data.options,filteredGroups,addonCategory]);
  const stats = useMemo(() => ({ active:reportOrders.filter(o=>!['completed','cancelled'].includes(String(o.status).toLowerCase())).length, sales:reportOrders.filter(o=>String(o.status).toLowerCase()!=='cancelled').reduce((s,o)=>s+Number(o.subtotal||0),0), completed:reportOrders.filter(o=>String(o.status).toLowerCase()==='completed').length }), [reportOrders]);
  const downloadReport = () => { const rows=[['Order','Time','Customer','Contact','City','Barangay','Address','Items','Add-ons','Item remarks','Order remarks','Status','Total'],...reportOrders.map(o=>[o.order_number,o.created_at,o.customer_name,o.contact_number,o.city,o.barangay,o.house_number,(o.items||[]).map(i=>`${i.quantity}x ${i.name}`).join('; '),(o.items||[]).flatMap(i=>(i.selected_options||[]).map(x=>`${i.name}: ${x.option_name} (+${x.price||0})`)).join('; '),(o.items||[]).filter(i=>i.remarks).map(i=>`${i.name}: ${i.remarks}`).join('; '),o.order_remarks||'',o.status,o.subtotal])]; const csv=rows.map(row=>row.map(cell=>`"${String(cell??'').replace(/"/g,'""')}"`).join(',')).join('\r\n'); const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); const a=document.createElement('a');a.href=url;a.download=`meal-guides-orders-${reportDate}.csv`;a.click();URL.revokeObjectURL(url); };
  const updateStatus = async (order_number, new_status) => { const current=orders.find(o=>String(o.order_number)===String(order_number)); if(String(current?.status).toLowerCase()==='completed') return; const previous=orders; setOrders(rows=>rows.map(o=>String(o.order_number)===String(order_number)?{...o,status:new_status}:o)); try { await request('updateOrderStatus',{order_number,new_status}); } catch(e){setOrders(previous);setError(e.message);} };
  const save = async () => { setSaving(true); setError(''); try { const map={restaurant:'saveRestaurant',category:'saveCategory',menu:'saveMenuItem',group:'saveOptionGroup',option:'saveOption'}; await request(map[editor.type],{record:editor.record}); setEditor(null); await load(); } catch(e){setError(e.message);} finally{setSaving(false);} };
  const edit = (type, record={}) => { const restaurantId=menuRestaurant!=='all'?menuRestaurant:data.restaurants[0]?.restaurant_id||''; const firstCategory=data.categories.find(category=>String(category.restaurant_id)===String(restaurantId)); const selectedCategory=addonCategory!=='all'?addonCategory:data.categories[0]?.category_id||''; const selectedGroup=data.optionGroups.find(group=>String(group.category_id)===String(selectedCategory))?.group_id||data.optionGroups[0]?.group_id||''; const defaults={restaurant:{restaurant_id:'',name:'',address:'',latitude:'',longitude:'',delivery_radius_km:10,logo_url:'',banner_url:'',description:'',active:'yes'},category:{category_id:'',restaurant_id:restaurantId,name:'',active:'yes',sort_order:1},menu:{item_id:'',restaurant_id:restaurantId,category_id:firstCategory?.category_id||'',name:'',description:'',base_price:'',photo_url:'',active:'yes'},group:{group_id:'',category_id:selectedCategory,item_id:'',group_name:'',selection_type:'multiple',required:'no',sort_order:1},option:{option_id:'',group_id:selectedGroup,option_name:'',price:0,sort_order:1}}; setEditor({type,record:{...defaults[type],...record}}); };
  const logout = async () => { localStorage.removeItem(CACHE_KEY); await fetch('/api/admin/auth',{method:'DELETE'}); window.location.reload(); };

    return <main className="admin-page"><aside className="admin-sidebar"><div className="admin-brand"><Image src="/the-meal-guides-logo.png" alt="" width={62} height={45}/><div><strong>meal guides</strong><small>Kitchen admin</small></div></div><nav>{[['orders',ClipboardList,'Orders'],['guests',UserRound,'Guests'],['restaurants',Store,'Restaurants'],['menu',Utensils,'Menu & pricing'],['addons',Layers3,'Add-ons & extras']].map(([id,Icon,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={20}/><span>{label}</span></button>)}</nav><div className="admin-sidebar-actions"><a href="/" className="admin-store-link"><ChefHat size={18}/> View storefront</a><button onClick={logout} className="admin-logout"><LogOut size={18}/> Sign out</button></div></aside>
    <section className="admin-workspace"><header className="admin-topbar"><div><p className="kicker">Control center</p><h1>{tab==='orders'?'Live orders':tab==='guests'?'Guest information':tab==='restaurants'?'Restaurants':tab==='menu'?'Menu & pricing':'Add-ons & extras'}</h1></div><button className="admin-refresh" onClick={load} disabled={loading}>{loading?<Loader2 className="spin"/>:<RefreshCw/>}<span>Refresh</span></button></header>
      {error&&<div className="admin-alert"><span>{error}</span><button onClick={()=>setError('')}><X size={18}/></button></div>}
      {tab==='orders'&&<>
        <div className="report-toolbar"><label><CalendarDays/><span>Report date</span><input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label><button onClick={downloadReport} disabled={!reportOrders.length}><Download/> Download daily report</button></div>
        <div className="admin-stats"><article><ClipboardList/><span>Active on selected day</span><strong>{stats.active}</strong></article><article><CircleDollarSign/><span>Total ordered on selected day</span><strong>{money(stats.sales)}</strong></article><article><Check/><span>Completed on selected day</span><strong>{stats.completed}</strong></article></div>
        <div className="admin-panel"><div className="admin-panel-head"><div><h2>Orders for {new Date(`${reportDate}T12:00:00`).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}</h2><p>Open an order to see every item, add-on, address, and remark.</p></div><span className="live-badge"><i/> {reportOrders.length} orders</span></div>{loading?<AdminLoading/>:<div className="order-table">{reportOrders.length===0?<CollectionEmpty label="orders for this date"/>:reportOrders.slice().reverse().map(order=>{const locked=String(order.status).toLowerCase()==='completed';const open=expandedOrder===order.order_number;return <article className={`admin-order-wrap ${locked?'order-locked':''}`} key={order.order_number}><div className="admin-order"><div className="admin-order-number"><small>Order</small><strong>#{order.order_number}</strong><span>{order.created_at?new Date(order.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</span></div><div><strong>{order.customer_name}</strong><p>{order.contact_number} · {order.barangay}, {order.city}</p><small>{order.items?.map(i=>`${i.quantity}× ${i.name}`).join(' · ')}</small></div><b>{money(order.subtotal)}</b><div className="order-actions"><button className="details-button" onClick={()=>setExpandedOrder(open?null:order.order_number)}><Eye/> {open?'Hide':'Details'}</button>{locked?<div className="completed-lock"><LockKeyhole size={16}/><span>Completed</span><small>Locked</small></div>:<label className={`status-select status-${order.status}`}><select value={String(order.status).toLowerCase()} onChange={e=>updateStatus(order.order_number,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><ChevronDown size={16}/></label>}</div></div>{open&&<OrderDetails order={order}/>}</article>})}</div>}</div>
      </>}
      {tab==='guests'&&<div className="admin-panel"><div className="admin-panel-head"><div><div className="title-with-count"><h2>Consented guest profiles</h2><span>{data.guests.length}</span></div><p>Delivery and contact details submitted by guests, with their visit history.</p></div></div>{loading?<AdminLoading/>:data.guests.length===0?<CollectionEmpty label="guest profiles"/>:<div className="guest-admin-grid">{data.guests.map(guest=><article className="guest-admin-card" key={guest.guest_id}><header><span><UserRound size={18}/></span><div><h3>{guest.customer_name}</h3><small>{Number(guest.visit_count||1)} {Number(guest.visit_count||1)===1?'visit':'visits'} · Last seen {new Date(guest.last_visited_at).toLocaleString()}</small></div></header><p><Mail size={16}/><a href={`mailto:${guest.customer_email}`}>{guest.customer_email}</a></p><p><Phone size={16}/><a href={`tel:${guest.contact_number}`}>{guest.contact_number}</a></p><p><MapPin size={16}/><span>{guest.house_number}, {guest.barangay}, {guest.city}</span></p><footer>Consent recorded {new Date(guest.consent_at).toLocaleString()}</footer></article>)}</div>}</div>}
      {tab==='restaurants'&&<AdminCollection title="All restaurant brands" count={data.restaurants.length} emptyLabel="restaurants" description="Every active and hidden restaurant from the Restaurants sheet." action="Add restaurant" onAdd={()=>edit('restaurant')} loading={loading}>{data.restaurants.map(r=><article className="entity-card" key={r.restaurant_id}><div className="entity-image">{normalizeImageUrl(r.logo_url)?<Image src={normalizeImageUrl(r.logo_url)} alt="" fill sizes="76px" unoptimized referrerPolicy="no-referrer"/>:<Store/>}</div><div><span className={`entity-status ${r.active==='yes'?'on':''}`}>{r.active==='yes'?'Active':'Hidden'}</span><h3>{r.name}</h3><p>{r.description}</p><small>{r.restaurant_id}</small></div><button onClick={()=>edit('restaurant',r)}><Settings2/> Edit</button></article>)}</AdminCollection>}
      {tab==='menu'&&<><div className="admin-filter-bar"><span><Filter size={17}/> Showing menu for</span><select value={menuRestaurant} onChange={event=>setMenuRestaurant(event.target.value)}><option value="all">All restaurants</option>{data.restaurants.map(restaurant=><option value={String(restaurant.restaurant_id)} key={restaurant.restaurant_id}>{restaurant.name}</option>)}</select><small>{filteredMenuItems.length} items · {filteredCategories.length} categories</small></div><AdminCollection title="Menu categories" count={filteredCategories.length} emptyLabel="categories for this restaurant" description="Create categories first, then assign menu items from a dropdown." action="Create category" onAdd={()=>edit('category')} loading={loading}>{filteredCategories.map(category=><article className="compact-entity" key={category.category_id}><div><span>{category.active==='yes'?'Active':'Hidden'}</span><h3>{category.name}</h3><p>{data.restaurants.find(r=>String(r.restaurant_id)===String(category.restaurant_id))?.name||category.restaurant_id}</p></div><button onClick={()=>edit('category',category)}>Edit</button></article>)}</AdminCollection><AdminCollection title="Menu items" count={filteredMenuItems.length} emptyLabel="menu items for this restaurant" description="Active and hidden items for the selected restaurant." action="Add menu item" onAdd={()=>edit('menu')} loading={loading}>{filteredMenuItems.map(item=><article className="entity-card" key={item.item_id}><div className="entity-image">{normalizeImageUrl(item.photo_url)?<Image src={normalizeImageUrl(item.photo_url)} alt="" fill sizes="76px" unoptimized referrerPolicy="no-referrer"/>:<Utensils/>}</div><div><span className={`entity-status ${item.active==='yes'?'on':''}`}>{item.active==='yes'?'Active':'Hidden'}</span><h3>{item.name}</h3><p>{data.categories.find(c=>String(c.category_id)===String(item.category_id))?.name||item.category} · {money(item.base_price)}</p><small>{data.restaurants.find(r=>String(r.restaurant_id)===String(item.restaurant_id))?.name||item.restaurant_id}</small></div><button onClick={()=>edit('menu',item)}><Settings2/> Edit</button></article>)}</AdminCollection></>}
      {tab==='addons'&&<><div className="admin-filter-bar"><span><Filter size={17}/> Filter add-ons by</span><select value={addonCategory} onChange={event=>setAddonCategory(event.target.value)}><option value="all">All categories</option>{data.restaurants.map(restaurant=><optgroup label={restaurant.name} key={restaurant.restaurant_id}>{data.categories.filter(category=>String(category.restaurant_id)===String(restaurant.restaurant_id)).map(category=><option value={String(category.category_id)} key={category.category_id}>{category.name}</option>)}</optgroup>)}</select><small>{filteredGroups.length} groups · {filteredOptions.length} choices</small></div><div className="addon-columns"><AdminCollection title="Category add-on groups" count={filteredGroups.length} emptyLabel="option groups for this category" description="Groups belonging to the selected category." action="Add group" onAdd={()=>edit('group')} loading={loading}>{filteredGroups.map(g=><article className="compact-entity" key={g.group_id}><div><span>{g.selection_type} · {g.required==='yes'?'required':'optional'}</span><h3>{g.group_name}</h3><p>{data.categories.find(c=>c.category_id===g.category_id)?.name||'Legacy item group'}</p></div><button onClick={()=>edit('group',g)}>Edit</button></article>)}</AdminCollection><AdminCollection title="Choices & extras" count={filteredOptions.length} emptyLabel="choices or extras for this category" description="Choices connected to the visible option groups." action="Add option" onAdd={()=>edit('option')} loading={loading}>{filteredOptions.map(o=><article className="compact-entity" key={o.option_id}><div><span>{money(o.price)}</span><h3>{o.option_name}</h3><p>{data.optionGroups.find(g=>g.group_id===o.group_id)?.group_name||o.group_id}</p></div><button onClick={()=>edit('option',o)}>Edit</button></article>)}</AdminCollection></div></>}
    </section>{editor&&<Editor editor={editor} setEditor={setEditor} data={data} save={save} saving={saving}/>}</main>;
}
function OrderDetails({order}){return <div className="admin-order-details"><div className="order-detail-section"><h3>Items & add-ons</h3>{(order.items||[]).map((item,index)=><div className="detailed-item" key={`${item.item_id}-${index}`}><span>{item.quantity}×</span><div><strong>{item.name}</strong>{item.selected_options?.length?<ul>{item.selected_options.map((option,i)=><li key={`${option.option_id}-${i}`}>{option.option_name}{Number(option.price)>0?` (+${money(option.price)})`:''}</li>)}</ul>:<small>No add-ons</small>}{item.remarks&&<p><b>Item remark:</b> {item.remarks}</p>}</div><b>{money(item.total_price)}</b></div>)}</div><div className="order-detail-section"><h3>Customer & address</h3><p><strong>{order.customer_name}</strong><br/>{order.contact_number}<br/>{order.house_number}, {order.barangay}, {order.city}</p>{order.landmark&&<p><b>Landmark:</b> {order.landmark}</p>}</div><div className="order-detail-section full"><h3>Order remarks</h3><p>{order.order_remarks||'No order remarks.'}</p></div></div>}
function AdminLoading(){return <div className="admin-loading"><Loader2 className="spin"/> Loading live data…</div>}
function AdminCollection({title,count,emptyLabel,description,action,onAdd,loading,children}){return <div className="admin-panel"><div className="admin-panel-head"><div><div className="title-with-count"><h2>{title}</h2>{Number.isFinite(count)&&<span>{count}</span>}</div><p>{description}</p></div><button className="admin-add" onClick={onAdd}><Plus/> {action}</button></div>{loading?<AdminLoading/>:count===0?<CollectionEmpty label={emptyLabel}/>:<div className="entity-grid">{children}</div>}</div>}
function CollectionEmpty({label}){return <div className="collection-empty"><Layers3/><strong>No {label} yet</strong><span>Create the first one using the button above.</span></div>}
function Editor({editor,setEditor,data,save,saving}) {
  const { type, record } = editor;
  const idFields = { restaurant:'restaurant_id', category:'category_id', menu:'item_id', group:'group_id', option:'option_id' };
  const set = (key,value) => setEditor({...editor,record:{...record,[key]:value}});
  const configs = {
    restaurant:[['name','Restaurant name','text'],['address','Restaurant address','text'],['latitude','Latitude','number'],['longitude','Longitude','number'],['delivery_radius_km','Delivery radius (km)','number'],['logo_url','Logo URL (restaurant cards)','url'],['banner_url','Banner URL (restaurant page cover)','url'],['description','Description','textarea'],['active','Status','active']],
    category:[['restaurant_id','Restaurant','restaurant'],['name','Category name','text'],['active','Status','active'],['sort_order','Sort order','number']],
    menu:[['restaurant_id','Restaurant','restaurant'],['category_id','Category','category'],['name','Item name','text'],['description','Item description','textarea'],['base_price','Base price','number'],['photo_url','Photo URL','url'],['active','Status','active']],
    group:[['category_id','Applies to category','category'],['group_name','Group name','text'],['selection_type','Selection type','selection'],['required','Required','yesno'],['sort_order','Sort order','number']],
    option:[['group_id','Option group','group'],['option_name','Option name','text'],['price','Additional price','number'],['sort_order','Sort order','number']]
  };
  const categories = type === 'menu' && record.restaurant_id ? data.categories.filter(c => String(c.restaurant_id) === String(record.restaurant_id) && c.active === 'yes') : data.categories;
  const renderField = ([key,label,kind]) => <label key={key}><span>{label}</span>{
    kind==='textarea'?<textarea value={record[key]||''} onChange={e=>set(key,e.target.value)}/>:
    kind==='restaurant'?<select value={record[key]} onChange={e=>{const restaurantId=e.target.value;const nextCategory=type==='menu'?data.categories.find(category=>String(category.restaurant_id)===String(restaurantId)&&category.active==='yes')?.category_id||'':record.category_id;setEditor({...editor,record:{...record,restaurant_id:restaurantId,category_id:nextCategory}});}}>{data.restaurants.map(x=><option value={x.restaurant_id} key={x.restaurant_id}>{x.name}</option>)}</select>:
    kind==='category'?<select value={record[key]} onChange={e=>set(key,e.target.value)} required><option value="" disabled>Select a category</option>{categories.map(x=><option value={x.category_id} key={x.category_id}>{x.name}</option>)}</select>:
    kind==='group'?<select value={record[key]} onChange={e=>set(key,e.target.value)}>{data.optionGroups.map(x=><option value={x.group_id} key={x.group_id}>{x.group_name}</option>)}</select>:
    kind==='active'?<select value={record[key]} onChange={e=>set(key,e.target.value)}><option value="yes">Active</option><option value="no">Hidden</option></select>:
    kind==='selection'?<select value={record[key]} onChange={e=>set(key,e.target.value)}><option value="single">Single choice</option><option value="multiple">Multiple choice</option></select>:
    kind==='yesno'?<select value={record[key]} onChange={e=>set(key,e.target.value)}><option value="yes">Yes</option><option value="no">No</option></select>:
    <input type={kind} step={kind==='number'?'any':undefined} value={record[key]??''} onChange={e=>set(key,e.target.value)} required={!['logo_url','banner_url','photo_url','description'].includes(key)}/>
  }</label>;
  return <div className="admin-modal-bg"><section className="admin-modal"><header><div><p className="kicker">{record[idFields[type]]?'Edit':'Create'}</p><h2>{type==='group'?'Option group':type}</h2></div><button onClick={()=>setEditor(null)}><X/></button></header><div className="admin-form">{configs[type].map(renderField)}</div><footer><button className="secondary-button" onClick={()=>setEditor(null)}>Cancel</button><button className="primary-button" onClick={save} disabled={saving}>{saving?<Loader2 className="spin"/>:<Save/>} Save changes</button></footer></section></div>;
}
