'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import Image from 'next/image';
import { Check, ChevronLeft, ChevronRight, Minus, Plus, ShoppingBag, X } from 'lucide-react';
import { useCart } from '@/context/CartContext';
import { normalizeImageUrl } from '@/lib/images';
import { marketMoney, normalizeMarketCode } from '@/lib/markets';

export default function MenuClient({ items, restaurantId, restaurantName, restaurantSlug, marketCode }) {
  const [selectedItem, setSelectedItem] = useState(null);
  const [selections, setSelections] = useState({});
  const [quantity, setQuantity] = useState(1);
  const [remarks, setRemarks] = useState('');
  const [error, setError] = useState('');
  const categoryScroller = useRef(null);
  const { addItem } = useCart();
  const normalizedMarket=normalizeMarketCode(marketCode);
  const money=(value)=>marketMoney(value,normalizedMarket);
  const grouped = useMemo(() => items.reduce((acc, item) => { const key = item.category || 'Favorites'; (acc[key] ||= []).push(item); return acc; }, {}), [items]);
  useEffect(() => { if (!selectedItem) return; const close = (event) => event.key === 'Escape' && setSelectedItem(null); document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close); }; }, [selectedItem]);
  const optionTotal = selectedItem ? Object.values(selections).flat().reduce((sum, option) => sum + Number(option.price || 0), 0) : 0;
  const unitPrice = Number(selectedItem?.base_price || 0) + optionTotal;
  const openItem = (item) => { setSelectedItem(item); setSelections({}); setQuantity(1); setRemarks(''); setError(''); };
  const chooseOption = (group, option) => { setError(''); setSelections((current) => { if (group.selection_type === 'single') return { ...current, [group.group_id]: [option] }; const chosen = current[group.group_id] || []; return { ...current, [group.group_id]: chosen.some((entry) => String(entry.option_id) === String(option.option_id)) ? chosen.filter((entry) => String(entry.option_id) !== String(option.option_id)) : [...chosen, option] }; }); };
  const scrollCategories = (direction) => { const scroller=categoryScroller.current; if(!scroller) return; scroller.scrollBy({left:direction*Math.max(240,scroller.clientWidth*.72),behavior:'smooth'}); };
  const addToCart = () => { const missing = (selectedItem.option_groups || []).find((group) => group.required === 'yes' && !(selections[group.group_id] || []).length); if (missing) { setError(`Please choose an option for ${missing.group_name}.`); return; } const added = addItem({ restaurant_id: restaurantId, restaurant_name: restaurantName, restaurant_slug: restaurantSlug, market_code:normalizedMarket, item_id: selectedItem.item_id, name: selectedItem.name, base_price: Number(selectedItem.base_price), quantity, selected_options: Object.values(selections).flat(), remarks, unit_price: unitPrice, total_price: unitPrice * quantity }); if (!added) { setError('Your cart contains food from another kitchen. Complete that order first.'); return; } setSelectedItem(null); };

  return <>
    <div className="category-slider"><button className="category-arrow" onClick={()=>scrollCategories(-1)} aria-label="Show previous categories"><ChevronLeft/></button><nav className="category-chips" ref={categoryScroller} aria-label="Menu categories">{Object.keys(grouped).map((category) => <a href={`#${encodeURIComponent(category)}`} key={category}>{category}</a>)}</nav><button className="category-arrow" onClick={()=>scrollCategories(1)} aria-label="Show more categories"><ChevronRight/></button></div>
    <div className="menu-groups">{Object.entries(grouped).map(([category, categoryItems]) => <section className="menu-section" id={encodeURIComponent(category)} key={category}><div className="menu-section-title"><div><p className="kicker">On the menu</p><h2>{category}</h2></div><span>{categoryItems.length} {categoryItems.length === 1 ? 'dish' : 'dishes'}</span></div><div className="menu-list">{categoryItems.map((item) => <button className="menu-card" key={item.item_id} onClick={() => openItem(item)}><div className="menu-card-copy"><span className="menu-category">{item.category}</span><h3>{item.name}</h3>{item.description&&<p className="menu-description">{item.description}</p>}<p className="menu-price">{money(item.base_price)}</p><span className="customize-link">Customize <ChevronRight size={16} /></span></div><div className="menu-photo">{normalizeImageUrl(item.photo_url) ? <Image src={normalizeImageUrl(item.photo_url)} alt={item.name} fill sizes="(max-width: 699px) 30vw, 130px" unoptimized referrerPolicy="no-referrer" /> : <ShoppingBag size={30} />}<span className="add-bubble"><Plus size={20} /></span></div></button>)}</div></section>)}</div>
    {selectedItem && createPortal(<div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setSelectedItem(null)}><section className="item-modal" role="dialog" aria-modal="true" aria-labelledby="customize-title"><button className="icon-button modal-close" onClick={() => setSelectedItem(null)} aria-label="Close"><X /></button><div className="modal-scroll">{normalizeImageUrl(selectedItem.photo_url)&&<div className="modal-food-photo"><Image src={normalizeImageUrl(selectedItem.photo_url)} alt={selectedItem.name} fill sizes="(max-width: 699px) 100vw, 640px" unoptimized referrerPolicy="no-referrer"/></div>}<header className="modal-header"><div><p className="kicker">Make it yours</p><h2 id="customize-title">{selectedItem.name}</h2>{selectedItem.description&&<p className="modal-description">{selectedItem.description}</p>}<p>{money(selectedItem.base_price)} base price</p></div></header><div className="modal-options">
      {(selectedItem.option_groups || []).map((group) => <fieldset className="option-group" key={group.group_id}><legend><span>{group.group_name}</span><small>{group.required === 'yes' ? 'Required' : 'Optional'} · {group.selection_type === 'single' ? 'Choose one' : 'Choose any'}</small></legend><div className="option-list">{(group.options || []).map((option) => { const checked = (selections[group.group_id] || []).some((entry) => String(entry.option_id) === String(option.option_id)); return <label className={`option-row ${checked ? 'selected' : ''}`} key={option.option_id}><input type={group.selection_type === 'single' ? 'radio' : 'checkbox'} name={`group-${group.group_id}`} checked={checked} onChange={() => chooseOption(group, option)} /><span className="fake-control">{checked && <Check size={14} />}</span><span>{option.option_name}</span><strong>{Number(option.price) ? `+${money(option.price)}` : 'Free'}</strong></label>; })}</div></fieldset>)}
      <label className="remarks-field"><span>Item remarks <small>Optional</small></span><textarea value={remarks} onChange={(e) => setRemarks(e.target.value)} placeholder="e.g. Sauce on the side" maxLength={160} /></label>{error && <p className="form-error" role="alert">{error}</p>}</div></div><footer className="modal-footer"><div className="stepper"><button onClick={() => setQuantity((q) => Math.max(1, q - 1))} aria-label="Decrease quantity"><Minus size={18} /></button><strong>{quantity}</strong><button onClick={() => setQuantity((q) => q + 1)} aria-label="Increase quantity"><Plus size={18} /></button></div><button className="primary-button" onClick={addToCart}><span>Add to cart</span><strong>{money(unitPrice * quantity)}</strong></button></footer></section></div>, document.body)}
  </>;
}
